version: "3.8"

services:
  db_BerikovZ:
    image: postgres:15
    container_name: db_BerikovZ
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
      POSTGRES_DB: todo_db
    volumes:
      - db_data_BerikovZ:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_user -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app_BerikovZ:
    build:
      context: .
      dockerfile: Dockerfile_BerikovZ
    image: berikovz/todo-app:1.0
    container_name: app_BerikovZ
    restart: unless-stopped
    depends_on:
      db_BerikovZ:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db_BerikovZ:5432/todo_db
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_pass
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/tasks || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data_BerikovZ:
